# Generated by Django 5.2 on 2025-04-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurs', models.CharField(max_length=10)),
                ('number', models.IntegerField(max_length=10)),
                ('p_s', models.IntegerField(max_length=10)),
                ('n_l', models.IntegerField(max_length=10)),
                ('b', models.IntegerField(max_length=10)),
                ('n', models.IntegerField(max_length=10)),
                ('y', models.IntegerField(max_length=10)),
                ('k', models.IntegerField(max_length=10)),
                ('o', models.IntegerField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
