# Generated by Django 5.2 on 2025-04-23 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtorization', '0002_kurses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurses',
            old_name='number',
            new_name='number_of_kurs',
        ),
    ]
