# Generated by Django 5.1.3 on 2025-04-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtorization', '0003_rename_number_kurses_number_of_kurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='list_password',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
