# Generated by Django 5.1.3 on 2025-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtorization', '0004_customuser_list_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurses',
            name='b',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurses',
            name='k',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurses',
            name='n',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurses',
            name='n_l',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurses',
            name='number_of_kurs',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurses',
            name='o',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurses',
            name='p_s',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='kurses',
            name='y',
            field=models.IntegerField(),
        ),
    ]
