# Generated by Django 5.1.3 on 2025-05-04 11:47

import avtorization.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtorization', '0005_alter_kurses_b_alter_kurses_k_alter_kurses_n_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Никнейм может содержать буквы, цифры, пробелы и символы @/./+/-/_ (3-50 символов).', max_length=150, unique=True, validators=[avtorization.validators.validate_username_with_spaces], verbose_name='Никнейм'),
        ),
    ]
