# Generated by Django 5.1.3 on 2025-05-09 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtorization', '0006_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=30)),
                ('absenceTime', models.DateField()),
                ('course', models.IntegerField()),
                ('Kurses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avtorization.kurses')),
            ],
        ),
    ]
