# Generated by Django 5.1.3 on 2025-05-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avtorization', '0007_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='course',
        ),
    ]
