# Generated by Django 5.2 on 2025-05-13 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avtorization', '0008_remove_persons_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
